address: :443
http_redirect_addr: :80

authenticate_service_url: https://auth.ztna.lab

cookie_secret: ${POMERIUM_COOKIE_SECRET}
shared_secret: ${POMERIUM_SHARED_SECRET}

idp_provider: oidc
idp_provider_url: http://keycloak:8080/realms/ztna
idp_client_id: pomerium
idp_client_secret: ${POMERIUM_IDP_CLIENT_SECRET}

routes:
  - from: https://dev.ztna.lab
    to: http://192.168.100.20:5001
    pass_identity_headers: true
    policy:
      allow:
        or:
          - groups:
              has: dev-users
          - groups:
              has: admins

  - from: https://rh.ztna.lab
    to: http://192.168.100.20:5002
    pass_identity_headers: true
    policy:
      allow:
        or:
          - groups:
              has: rh-users
          - groups:
              has: admins
