# ============================================
#   POMERIUM CONFIG - ZTNA LAB PFE
#   Keycloak OIDC + Zero Trust Policy
# ============================================

address: :443
insecure_server: :80
authenticate_service_url: https://auth.ztna.lab

# --- Secrets obligatoires ---
cookie_secret: T/DenVBWdeNWX8AhfQYvSksYqBaV69c0rlbeRHN4h54=
shared_secret: anM+JBUuGmZ5L0OeiT74CZ8b5eHGbs6qR02J8oQ5oQI=

# --- Identity Provider: Keycloak OIDC ---
idp_provider: oidc
idp_provider_url: http://192.168.100.10:8080/realms/ztna
idp_client_id: pomerium
idp_client_secret: bcmt5inj9taEvkcmoehm4NttZQIuLrae

# --- Routes + Zero Trust Policy ---
routes:
  - from: https://app.ztna.lab
    to: http://192.168.100.20:80
    pass_identity_headers: true
    policy:
      allow:
        or:
          - email:
              is: admin@ztna.lab
          - email:
              is: user@ztna.lab

  - from: https://auth.ztna.lab
    to: http://127.0.0.1:80
    pass_identity_headers: true
